version: "2.1"

services:
  namenode:
    build: ./namenode
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    
  datanode:
    build: ./datanode
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop.env
    ports:
      - "8089:8088"
  
  nodemanager:
    build: ./nodemanager
    container_name: nodemanager
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop.env
    ports:
      - "8042:8042"

  historyserver:
    build: ./historyserver
    container_name: historyserver
    depends_on:
      - namenode
      - datanode
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
